### ISSUE TITLE
Multiple Line Plots

### ISSUE THREAD

**Issue by rgreenn** [juniors90/Flask-Plots#1]
Hi,

Is it possible to make multiple line plots (I've been using errorbars() to get a line plot) in the same graph? If not are there any future plans to include this functionality?

Thanks

**Comment by juniors90** [comment]
Dear @rgreenn 

If it is possible to make multi-line plots. Could you show me the exact example of the plot you want from Matplotlib? A url would help me to give me an idea of ​​what you want to achieve.

Juniors

**Comment by rgreenn** [comment]
I appreciate the quick reply.

I figured it out. I did not realize you just have to redefine "ax" for each new line you want. I also created a legend. Using the errorbar() function from sample_app/app.py as an example where my additions are marked with the "added below" comment (I did not test this, just wanted to give an example to anyone that may see this in future):

```
@app.route("/errorbar")
def errorbar():
    # make data
    np.random.seed(1)
    x = [2, 4, 6]
    y = [3.6, 5, 4.2]
    yerr = [0.9, 1.2, 0.5]
    
    # added below
    x1 = [3, 5, 7]
    y1 = [4.6, 6, 5.2]
    y1err = [0.9, 1.2, 0.5]

    # Plot
    fig = Figure()
    ax = fig.subplots()
    ax = plots.errorbar(
        fig,
        x=x,
        y=y,
        errorbar_kws={"yerr": yerr, "fmt": "o", "linewidth": 2, "capsize": 6},
    )

    # added below
    ax = plots.errorbar(
        fig,
        x=x1,
        y=y1,
        errorbar_kws={"yerr": yerr, "fmt": "o", "linewidth": 2, "capsize": 6},
    )

    ax.set(
        xlim=(0, 8),
        xticks=np.arange(1, 8),
        ylim=(0, 8),
        yticks=np.arange(1, 8),
    )

    # added below
    ax.legend(['first', 'second'])

    ax.set_title("Errorbar Chart")
    data = plots.get_data(fig)
    return render_template_string(
        """
        {% from 'plots/utils.html' import render_img %}
        {{ render_img(data=data, alt_img='my_img') }}
        """,
        data=data,
    )
```
